## 数据来源
数据来源：http://t.cn/Ezyacne

数据包含2个csv文件：

>train_set.csv：此数据集用于训练模型，每一行对应一篇文章。文章分别在“字”和“词”的级别上做了脱敏处理。共有四列：
第一列是文章的索引(id)，第二列是文章正文在“字”级别上的表示，即字符相隔正文(article)；第三列是在“词”级别上的表示，即词语相隔正文(word_seg)；第四列是这篇文章的标注(class)。
注：每一个数字对应一个“字”，或“词”，或“标点符号”。“字”的编号与“词”的编号是独立的！

>test_set.csv：此数据用于测试。数据格式同train_set.csv，但不包含class。
注：test_set与train_test中文章id的编号是独立的。

友情提示：请不要尝试用excel打开这些文件！由于一篇文章太长，excel可能无法完整地读入某一行！

## 数据加载

In [9]:
# import pandas as pd

# #datas=pd.read_csv('./Data/new_data/train_set.csv') # 数据大，爆内存CParserError: Error tokenizing data. C error: out of memory

# datas=pd.read_csv('./Data/new_data/train_set.csv',nrows=10000)  # 读前10000行
# datas.head()

id                                            article  \
0   0  7368 1252069 365865 755561 1044285 129532 1053...   
1   1  581131 165432 7368 957317 1197553 570900 33659...   
2   2  7368 87936 40494 490286 856005 641588 145611 1...   
3   3  299237 760651 299237 887082 159592 556634 7489...   
4   4  7368 7368 7368 865510 7368 396966 995243 37685...   

                                            word_seg  class  
0  816903 597526 520477 1179558 1033823 758724 63...     14  
1  90540 816903 441039 816903 569138 816903 10343...      3  
2  816903 1012629 957974 1033823 328210 947200 65...     12  
3  563568 1239563 680125 780219 782805 1033823 19...     13  
4  816903 816903 816903 139132 816903 312320 1103...     12

In [1]:
import pandas as pd
datas = pd.DataFrame()
for chunk in pd.read_csv('./Data/new_data/train_set.csv', chunksize=1000):
    datas = pd.concat([datas, chunk], ignore_index=True)

In [2]:
datas.shape

(102277, 4)

## TF-IDF

In [3]:
datas['article'].head()

0    7368 1252069 365865 755561 1044285 129532 1053...
1    581131 165432 7368 957317 1197553 570900 33659...
2    7368 87936 40494 490286 856005 641588 145611 1...
3    299237 760651 299237 887082 159592 556634 7489...
4    7368 7368 7368 865510 7368 396966 995243 37685...
Name: article, dtype: object

In [4]:
datas[['article']].head()

article
0  7368 1252069 365865 755561 1044285 129532 1053...
1  581131 165432 7368 957317 1197553 570900 33659...
2  7368 87936 40494 490286 856005 641588 145611 1...
3  299237 760651 299237 887082 159592 556634 7489...
4  7368 7368 7368 865510 7368 396966 995243 37685...

In [ ]:
# word_seg
# from sklearn.feature_extraction.text import CountVectorizer
# count_vect=CountVectorizer()
# word_seg_counts=count_vect.fit_transform(datas['word_seg']) # 词频矩阵
# word_seg_counts.toarray()

In [1]:
# # tf-idf
# from sklearn.feature_extraction.text import TfidfTransformer
# tfidf_transformer=TfidfTransformer()
# word_seg_tfidf=tfidf_transformer.fit_transform(word_seg_counts)

# word_seg_tfidf.toarray()

NameError: name 'word_seg_counts' is not defined

## word2vec

参考：https://github.com/Heitao5200/DGB/blob/master/feature/feature_code/train_word2vec.py

In [7]:
# def transfer(word_seg):
#     return word_seg.split()

# word_seg_list=list(datas['word_seg'].apply(transfer))

In [14]:
# word_seg_list[1]

['90540',
 '816903',
 '441039',
 '816903',
 '569138',
 '816903',
 '1034376',
 '997489',
 '382714',
 '1236006',
 '520477',
 '132364',
 '1207796',
 '89613',
 '1033299',
 '834740',
 '133940',
 '816903',
 '848000',
 '386932',
 '520477',
 '31046',
 '766772',
 '748483',
 '481786',
 '701424',
 '522428',
 '764656',
 '572782',
 '266161',
 '432549',
 '457828',
 '968083',
 '397939',
 '323159',
 '1033823',
 '925313',
 '520477',
 '848000',
 '220238',
 '701424',
 '500399',
 '133940',
 '816903',
 '1256303',
 '520477',
 '1243427',
 '520477',
 '487094',
 '993110',
 '477703',
 '768219',
 '133940',
 '1034376',
 '140644',
 '98991',
 '1207796',
 '569876',
 '1130139',
 '1033823',
 '257190',
 '878073',
 '585102',
 '1105940',
 '985047',
 '834740',
 '520477',
 '506606',
 '266784',
 '781202',
 '566120',
 '768219',
 '133940',
 '816903',
 '31046',
 '422170',
 '441513',
 '703615',
 '847492',
 '520477',
 '300241',
 '54111',
 '1278725',
 '173393',
 '652252',
 '133940',
 '1014945',
 '1231069',
 '1046814',
 '1033823',

In [8]:
# import gensim
# model = gensim.models.Word2Vec(word_seg_list,size=100, window=5, min_count=5, workers=8, sg=0, iter=5)


In [5]:
from sklearn.cross_validation import train_test_split

train_datas,test_datas = train_test_split(datas, test_size=0.3, random_state=2019)

train_datas.shape, test_datas.shape

/usr/local/lib/python3.6/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


((71593, 4), (30684, 4))

In [6]:
train_datas.head()

id                                            article  \
96040  96040  556634 837240 359838 658824 873355 856005 1177...   
91212  91212  1058423 887082 1044285 891719 697742 316564 56...   
28207  28207  598093 968221 316709 986218 7368 7368 144506 1...   
88425  88425  370832 370832 370832 7368 478062 569999 114886...   
57653  57653  1136931 441856 477606 348926 1009224 89539 466...   

                                                word_seg  class  
96040  3849 460600 193705 1033823 1226134 218823 5542...     14  
91212  539278 520477 1070929 477703 184574 711974 878...     19  
28207  91625 533560 816903 816903 208199 203284 81690...     13  
88425  629837 629837 629837 816903 1055804 1033823 83...     12  
57653  876555 1103075 990092 1134471 66495 520477 859...     18

In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer
model=TfidfVectorizer()
model.fit(datas["word_seg"])

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), norm='l2', preprocessor=None, smooth_idf=True,
        stop_words=None, strip_accents=None, sublinear_tf=False,
        token_pattern='(?u)\\b\\w\\w+\\b', tokenizer=None, use_idf=True,
        vocabulary=None)

In [49]:
X_train = model.transform(train_datas["word_seg"])
Y_train = train_datas["class"]-1

X_test = model.transform(test_datas["word_seg"])
Y_test = test_datas["class"]-1

In [20]:
import _pickle as pk
datapk = (X_train, Y_train, X_test, Y_test)
pk.dump(datapk, open("train_data.pk", "wb"))

In [16]:
# Logistic Regression
from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression()
logreg.fit(X_train, Y_train)
Y_pred1 = logreg.predict(X_test)
acc_log = round(logreg.score(X_train, Y_train) * 100, 2)
acc_log

83.019999999999996

In [18]:
!ls -ahl ./Data/new_data

total 5400576
drwxr-xr-x  4 liuyue  staff   128B Mar  1 20:32 .
drwxr-xr-x  3 liuyue  staff    96B Mar  1 20:33 ..
-rw-r--r--  1 liuyue  staff   1.3G Mar  1 20:32 test_set.csv
-rw-r--r--  1 liuyue  staff   1.3G Mar  1 20:32 train_set.csv


In [40]:
set(Y_train)

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19}

In [50]:
import lightgbm as lgb

dtrain = lgb.Dataset(X_train, label=Y_train)

params = {
        'task': 'train',
        'boosting_type': 'gbdt',
        'objective': 'multiclass',
        'num_class':19,
        'learning_rate': 0.1,
        'max_depth': 8,
        'verbose': 3
    }
print('Start training...')
    # train
gbm = lgb.train(params,
                    dtrain,
                    num_boost_round=100)
gbm.save_model('lgb_model')

Start training...


In [69]:
y_pred = gbm.predict(X_test)

In [70]:
import numpy as np
y_pred = np.asarray(list(map(lambda x: np.argmax(x), y_pred)))

In [71]:
y_pred

array([11,  2,  9, ...,  4, 12,  1])

In [73]:
from sklearn.metrics import accuracy_score
score = accuracy_score(Y_test.values, y_pred)
print(score)

0.739831834181


## 预测

In [76]:
test_df = pd.DataFrame()
for chunk in pd.read_csv('./Data/new_data/test_set.csv', chunksize=1000):
    test_df = pd.concat([test_df, chunk], ignore_index=True)

In [77]:
test_df.head()

id                                            article  \
0   0  7368 146447 316564 42610 55736 297797 93042 53...   
1   1  985531 473628 1044285 1121849 206763 462208 11...   
2   2  7368 7368 7368 7368 7368 7368 7368 7368 7368 7...   
3   3  529819 1226459 856005 1177293 663773 272235 93...   
4   4  42610 1252069 1077049 955883 1125260 1044285 2...   

                                            word_seg  
0  816903 565958 726082 764656 335008 75094 20282...  
1  729468 520477 529032 101368 335130 520477 1113...  
2  816903 816903 816903 816903 816903 816903 8169...  
3  231664 1033823 524850 330478 507199 520477 618...  
4  545370 379223 162767 520477 1194630 1197475 11...

In [78]:
X_test_df = model.transform(test_df["word_seg"])

In [79]:
X_test_df.shape

(102277, 875122)

In [80]:
test_y_pred=gbm.predict(X_test_df)

In [84]:
test_y_pred_c = np.asarray(list(map(lambda x: np.argmax(x), test_y_pred)))

In [85]:
test_y_pred_c[:5]

array([ 4,  3, 11,  3,  4])

In [86]:
test_df['class'] = test_y_pred_c
test_df.head()

id                                            article  \
0   0  7368 146447 316564 42610 55736 297797 93042 53...   
1   1  985531 473628 1044285 1121849 206763 462208 11...   
2   2  7368 7368 7368 7368 7368 7368 7368 7368 7368 7...   
3   3  529819 1226459 856005 1177293 663773 272235 93...   
4   4  42610 1252069 1077049 955883 1125260 1044285 2...   

                                            word_seg  class  
0  816903 565958 726082 764656 335008 75094 20282...      4  
1  729468 520477 529032 101368 335130 520477 1113...      3  
2  816903 816903 816903 816903 816903 816903 8169...     11  
3  231664 1033823 524850 330478 507199 520477 618...      3  
4  545370 379223 162767 520477 1194630 1197475 11...      4

In [87]:
test_df_result = test_df.loc[:, ['id', 'class']]

In [88]:
test_df_result.head()

id  class
0   0      4
1   1      3
2   2     11
3   3      3
4   4      4

In [90]:
test_df_result.to_csv('./r_lgb_1.csv', index=False)

In [91]:
test_y_pred_c[:]=[x+1 for x in test_y_pred_c]

In [92]:
test_y_pred_c[:5]

array([ 5,  4, 12,  4,  5])

In [93]:
test_df['class'] = test_y_pred_c
test_df.head()

id                                            article  \
0   0  7368 146447 316564 42610 55736 297797 93042 53...   
1   1  985531 473628 1044285 1121849 206763 462208 11...   
2   2  7368 7368 7368 7368 7368 7368 7368 7368 7368 7...   
3   3  529819 1226459 856005 1177293 663773 272235 93...   
4   4  42610 1252069 1077049 955883 1125260 1044285 2...   

                                            word_seg  class  
0  816903 565958 726082 764656 335008 75094 20282...      5  
1  729468 520477 529032 101368 335130 520477 1113...      4  
2  816903 816903 816903 816903 816903 816903 8169...     12  
3  231664 1033823 524850 330478 507199 520477 618...      4  
4  545370 379223 162767 520477 1194630 1197475 11...      5

In [94]:
test_df_result = test_df.loc[:, ['id', 'class']]
test_df_result.to_csv('./r_lgb_2.csv', index=False)